# Generated by Django 5.2 on 2025-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['id'], 'verbose_name': 'Quote Item', 'verbose_name_plural': 'Quote Items'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('SE', 'Sent'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('EX', 'Expired'), ('CO', 'Converted to Order')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
